version: '3'
services:
   api:
       build: .
       ports:
       - 5000:5000
       volumes:
       - ${PATH_OF_SOURCE}/input/:/app/input
       - ${PATH_OF_SOURCE}/output/:/app/output
       - ${PATH_OF_SOURCE}/output/logs:/app/output/logs
       - ${PATH_OF_SOURCE}/output/number_of_lines:/app/number_of_lines
