version: '3'
services:
   api:
       build: .
       ports:
       - "5000:5000"
       volumes: 
       - ../input/:/app/input
       - ../output/:/app/output
       - ../output/logs:/app/output/logs
       - ../output/number_of_lines:/app/number_of_lines
